PL_MVC/Controllers/AseguradoraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class AseguradoraController : Controller
    {
        // GET: Empresa
        public ActionResult GetAll()
        {
            ML.Result result = BL.Aseguradora.GetAllEF();
            ML.Aseguradora aseguradora = new ML.Aseguradora();
            if (result.Correct)
            {
                aseguradora.Aseguradoras = result.Objects;
            }
            else
            {
                ViewBag.Message = "Error al cargar la informacion";
            }


            return View(aseguradora);
        }

        [HttpGet]
        public ActionResult Form(int? idAseguradora) //se usa el int? para que acepte valores null
        {
            if (idAseguradora == null)
            {

                return View();
            }

            else
            {
                ML.Result result = BL.Aseguradora.GetByIdEF(idAseguradora.Value);

                ML.Aseguradora aseguradora = new ML.Aseguradora();

                if (result.Correct)
                {
                    //Se tiene que hacer un unboxing del objeto que nos trajo el metodo de GEYBYID
                    aseguradora = (ML.Aseguradora)result.Object; //Se usa el object porque solo es 1 objeto 
                }
                else
                {
                    ViewBag.Message = "Error al cargar la informacion";
                }
                return View(aseguradora);
            }
        }

        [HttpPost]
        public ActionResult Form(ML.Aseguradora aseguradora) //se usa el int? para que acepte valores null
        {
            //ML.Usuario usuario = new ML.Usuario();

            if (aseguradora.IdAseguradora == 0)
            {
                ML.Result result = BL.Aseguradora.AddEF(aseguradora);
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error:" + result.Message;
                }

            }

            else
            {
                ML.Result result = BL.Aseguradora.UpdateEF(aseguradora);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }

            return PartialView("Modal");
        }

        public ActionResult Delete(ML.Aseguradora aseguradora)
        {
            ML.Result result = BL.Aseguradora.DelateEF(aseguradora);
            if (result.Correct)
            {
                ViewBag.Message = result.Message;
            }
            else
            {
                ViewBag.Message = "Error:" + result.Message;
            }
            return PartialView("Modal");
        }
    }
}

PL_MVC/Views/Aseguradora/GetAll.cshtml
@model ML.Aseguradora
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Aseguradora</h2>
    <p>Aqui podra ver los datos relacionados con la aseguradora asi como editar y eliminar</p>

    <div class=" row">
        <div style="float:right">
            @Html.ActionLink("Agregar", "Form", "Aseguradora", htmlAttributes: new { @class = "btn btn-success" }) @*Agregar un boton + *@
        </div>
    </div>

    <hr />

    <dir class=" row">
        <table class=" table table-responsive">
            <thead class="thead-dark">
                <tr>
                    @*<th>Hace referencia a las cabeceras de la tabla</th>*@
                    <th>Editar</th>
                    <th class=" hidden">IdAseguradora</th> @*se oculta el id del usuario ya que no es necesario el mostrarlo*@
                    <th>Nombre</th>
                    <th>Fecha de Creacion</th>
                    <th>Fecha de Modificacion</th>
                    <th class="hidden">IdUsuario</th>
                    <th>Nombre del Usuario</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Aseguradora aseguradora in Model.Aseguradoras)
                {
                    <tr>
                        <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Aseguradora", new { IdAseguradora = aseguradora.IdAseguradora})"></a></td>
                        <td class="hidden">@aseguradora.IdAseguradora</td>
                        <td>@aseguradora.NombreAseguradora</td> @*se concatena para que muestre todo junto*@
                        <td>@aseguradora.FechaCreacion</td>
                        <td>@aseguradora.FechaModificacion</td>
                        <td>@aseguradora.IdUsuario</td>
                        <td>@aseguradora.Usuario.NombreUsuario @aseguradora.Usuario.ApellidoPaternoU @aseguradora.Usuario.ApellidoMaternoU</td>
                        <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Aseguradora", new { IdAseguradora = aseguradora.IdAseguradora })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                    </tr>
                }
            <tbody>
        </table>
    </dir>
</div>
<h2>GetAll</h2>