PL_MVC/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class EmpresaController : Controller
    {
        // GET: Empresa
        public ActionResult GetAll()
        {
            ML.Result result = BL.Empresa.GetAllEF();
            ML.Empresa empresa = new ML.Empresa();
            if(result.Correct)
            {
               empresa.Empresas = result.Objects;
            }
            else
            {
                ViewBag.Message = "Error al cargar la informacion";
            }


            return View(empresa);
        }

        [HttpGet]
        public ActionResult Form(int? IdEmpresa) //se usa el int? para que acepte valores null
        {
            if (IdEmpresa == null)
            {

                return View();
            }

            else
            {
                ML.Result result = BL.Empresa.GetByIdEF(IdEmpresa.Value);

                ML.Empresa empresa = new ML.Empresa();

                if (result.Correct)
                {
                    //Se tiene que hacer un unboxing del objeto que nos trajo el metodo de GEYBYID
                    empresa = (ML.Empresa)result.Object; //Se usa el object porque solo es 1 objeto 
                }
                else
                {
                    ViewBag.Message = "Error al cargar la informacion";
                }
                return View(empresa);
            }
        }

        [HttpPost]
        public ActionResult Form(ML.Empresa empresa) //se usa el int? para que acepte valores null
        {
            //ML.Usuario usuario = new ML.Usuario();

            if (empresa.IdEmpresa == 0)
            {
                ML.Result result = BL.Empresa.AddEF(empresa);
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error:" + result.Message;
                }

            }

            else
            {
                ML.Result result = BL.Empresa.UpdateEF(empresa);

                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }

            return PartialView("Modal");
        }

        public ActionResult Delete(ML.Empresa empresa)
        {
            ML.Result result = BL.Empresa.DelateEF(empresa);
            if(result.Correct)
            {
                ViewBag.Message = result.Message;
            }
            else
            {
                ViewBag.Message = "Error:" +result.Message;
            }
            return PartialView("Modal");
        }
    }
}

PL_MVC/Views/Empresa/Form.cshtml
@model ML.Empresa
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h2>Form</h2>
    <p>Aqui puede ver y actualizar los datos de la empresa</p>

    <div class="row">
        <div class=" col-md-12">

            @using (Html.BeginForm("Form", "Empresa", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.IdEmpresa, new { @class = "hidden" }) @*LabelFor hace referencia a una etiqueta con texto*@

                            @Html.TextBoxFor(model => model.IdEmpresa, new { @class = "hidden form-control" }) @*Crea una caja de texto con el nombre que le indiquemos  y con un valor por defecto en el segundo parámetro.*@

                            @Html.ValidationMessageFor(model => model.IdEmpresa)

                        </div>

                    </div>

                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.NombreEmpresa)

                            @Html.TextBoxFor(model => model.NombreEmpresa, new { @class = "form-control", @id = "txtNombre" })

                            @Html.ValidationMessageFor(model => model.NombreEmpresa)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Telefono)

                            @Html.TextBoxFor(model => model.Telefono, new { @class = "form-control", @id = "txtNombre" })

                            @Html.ValidationMessageFor(model => model.Telefono)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Email)

                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @id = "txtNombre" })

                            @Html.ValidationMessageFor(model => model.Email)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.DireccionWeb)

                            @Html.TextBoxFor(model => model.DireccionWeb, new { @class = "form-control", @id = "txtNombre" })

                            @Html.ValidationMessageFor(model => model.DireccionWeb)

                        </div>

                    </div>
                    <div class="form-group">

                        <div class="col-md-3">

                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @*Se crea el boton de guardar*@

                            @Html.ActionLink("Regresar", "GetAll", "Empresa", htmlAttributes: new { @class = "btn btn-danger" })
                            @*Se crea el boton de regresar se regresa al metodo GetAll en el controlador de usuario*@
                        </div>

                    </div>

                </div>
            }

        </div>


    </div>

</div>

PL_MVC/Views/Empresa/GetAll.cshtml
@model ML.Empresa
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Empresa</h2>
    <p>Aqui podra ver los datos relacionados con la empresa asi como editar y eliminar</p>

    <div class=" row">
        <div style="float:right">
            @Html.ActionLink("Agregar", "Form", "Empresa", htmlAttributes: new { @class = "btn btn-success" }) @*Agregar un boton + *@
        </div>
    </div>

    <hr />

    <dir class=" row">
        <table class=" table table-responsive">
            <thead class="thead-dark">
                <tr>
                    @*<th>Hace referencia a las cabeceras de la tabla</th>*@
                    <th>Editar</th>
                    <th class=" hidden">IdEmpresa</th> @*se oculta el id del usuario ya que no es necesario el mostrarlo*@
                    <th>Nombre</th>
                    <th>Telefono</th>
                    <th>Email</th>
                    <th>Direccion Web</th>
                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Empresa empresa in Model.Empresas)
                {
                    <tr>
                        <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Empresa", new { IdEmpresa = empresa.IdEmpresa})"></a></td>
                        <td class="hidden">@empresa.IdEmpresa</td>
                        <td>@empresa.NombreEmpresa</td> @*se concatena para que muestre todo junto*@
                        <td>@empresa.Telefono</td>
                        <td>@empresa.Email</td>
                        <td>@empresa.DireccionWeb</td>
                        <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Empresa", new { IdEmpresa = empresa.IdEmpresa })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                    </tr>
                }
            <tbody>
        </table>
    </dir>
</div>

    <h2>GetAll</h2>

PL_MVC/Views/Empresa/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Empresa", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>